---
- name: Play 1 - "IOS Config Demo"
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Task 1
      cisco.ios.ios_config:
        lines:
          - "ip domain name test.com"
    
    - name: Task 2 - "Configure Interface with IP"
      cisco.ios.ios_config:
        lines:
          - description ansible_configured
          - ip address 2.2.2.2 255.255.255.0
        parents: interface GigabitEthernet0/1
        diff_against: startup
        save_when: modified
    
    - name: Task 3 - "Configure Multiple Interfaces"
      cisco.ios.ios_config:
        lines:
          - description backup_int
        parents: "{{ item }}"
        after: 
          - no shutdown
      with_items:
        - interface GigabitEthernet0/2
        - nterface GigabitEthernet0/3
