---

collections:
  - name: ansible.netcommon
    version:  5.3.0
  - name: ansible.utils
    version:  2.12.0
  - name: arista.eos
    version:  6.2.2
  - name: awx.awx
    version:  22.7.0
  - name: cisco.ios
    version:  4.6.1
  - name: cisco.iosxr
    version:  5.0.3
  - name: vyos.vyos
    version:  4.1.0
